name: Deploy Node Application

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Debug Secret Value
        run: "echo DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"

      - name: Login to docker hub 
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}}    
      - name: Build Docker Image
        run: docker build -t genishprakash/todolist-backend  .
      - name: Publish Image to docker hub
        run: docker push genishprakash/todolist-backend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull genishprakash/todolist-backend:latest 
      - name: Delete old container
        run: docker rm -f todolist-backend-container  
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name todolist-backend-container -e MONGO_PASSWORD=`${{ secrets.MONGO_PASSWORD }}` genishprakash/todolist-backend